export const GET_DOGS = "GET_DOGS";
export const GET_DETAIL = "GET_DETAIL";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const ADD_DOG = "ADD_DOG";
export const ORDER_BY_THING = "ORDER_BY_THING";
export const FILTER_TEMPERAMENT = "FILTER_TEMPERAMENT";
export const FILTER_CREATED = "FILTER_CREATED";
